export const TRIP_ACTIONS = {
  GET_TRIPS: 'GET_TRIPS',
  DELETE_TRIP: 'DELETE_TRIP',
  SAVE_UPDATE_TRIP: 'SAVE_UPDATE_TRIP',
  GET_TRIP_EXPENSES: 'GET_TRIP_EXPENSES',
  SAVE_UPDATE_TRIP_EXPENSES: 'SAVE_UPDATE_TRIP_EXPENSES',
  DELETE_TRIP_EXPENSE: 'DELETE_TRIP_EXPENSE'
}

export const INSTALLMENT_ACTIONS = {
  GET_INSTALLMENTS: 'GET_INSTALLMENTS',
  DELETE_INSTALLMENT: 'DELETE_INSTALLMENT',
  SAVE_UPDATE_INSTALLMENT: 'SAVE_UPDATE_INSTALLMENT',
  ISEXIST_INSTALLMENT: 'ISEXIST_INSTALLMENT'
}

export const USER_ACTIONS = {
  GET_USERS: 'GET_USERS'
}

export const AUTHENTICATION_ACTIONS = {
  AUTHENTICATE_USER: 'AUTHENTICATE_USER',
}

export const COMMON_ACTIONS = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  RESET_STATUS: '_RESET_STATUS',
  MODIFY: '_MODIFY'
}

export const NOTIFIER_ACTIONS = {
  TRIGGER_NOTIFIER_MESSAGE: 'TRIGGER_NOTIFIER_MESSAGE',
  CLOSE_NOTIFIER_MESSAGE: 'CLOSE_NOTIFIER_MESSAGE',
  REMOVE_NOTIFIER_MESSAGE: 'REMOVE_NOTIFIER_MESSAGE'
}