export const TRIP_ACTIONS = {
  GET_TRIPS: 'GET_TRIPS',
  DELETE_TRIP: 'DELETE_TRIP',
  SAVE_UPDATE_TRIP: 'SAVE_UPDATE_TRIP',
  GET_TRIP_EXPENSES: 'GET_TRIP_EXPENSES',
  SAVE_UPDATE_TRIP_EXPENSES: 'SAVE_UPDATE_TRIP_EXPENSES',
  DELETE_TRIP_EXPENSE: 'DELETE_TRIP_EXPENSE'
}

export const COMMON_ACTIONS = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  RESET_STATUS: '_RESET_STATUS',
  MODIFY: '_MODIFY'
}

export const NOTIFIER_ACTIONS = {
  TRIGGER_NOTIFIER_MESSAGE: 'TRIGGER_NOTIFIER_MESSAGE',
  CLOSE_NOTIFIER_MESSAGE: 'CLOSE_NOTIFIER_MESSAGE',
  REMOVE_NOTIFIER_MESSAGE: 'REMOVE_NOTIFIER_MESSAGE'
}