export const APP_MESSAGES = {
  INVALID_FORM: 'Fill all required fields to continue',
  USER_EXISTS_FORM: 'User already exists',
  FILE_QUEUE_PROCESSING: 'Files uploading.. Wait until the process completed',
  NO_VALID_FILE: 'Upload at least one file to continue',
  ADD_SAMPLE_REVIEW_SUCCESS: 'Review added successfully.',
  COMMENT_DISABLED_WARNING: 'Creator has disabled the commenting feature on this item.',
  NO_DATA: 'No data found',
  DATA_SUCCESS: 'Data Updated Successfully',
  REMOVE_DEFAULT_DEPARTMENT: 'Cannot remove the default department',
  VALID_EMAIL: 'Please enter a valid email',
  THUMBNAIL_SAMPLE_FILE_DELETE_ERROR: 'Cannot delete isThumbnail sample file. Change isThumbnail to delete the file.',
  LAST_SAMPLE_FILE_DELETE_ERROR: 'Cannot delete the file. At least one sample file should exist.',
  UNDEFINED_SAMPLE_REF: 'Unable to find sample reference number to proceed',
  SAMPLE_DELETE_SUCCESS: 'Sample deleted successfully',
  EMPTY_CART: 'No Items available in your cart.',
  ADD_CART_ITEM_SUCCESS: 'Item added successfully to your cart',
  ASSIGN_GLOBAL: 'Please select a user and permission level to continue ',
  ASSIGN_CUSTOMER: 'Please select a customer to continue',
  ASSIGN_DEPARTMENT: 'Please select a department to continue',
  INVALID_MOBILE: 'Please enter a valid phone number',
  DESIGN_REPORT_UPLOAD_EMPTY_WARNING: 'Please add least one file to continue',
  DESIGN_REPORT_UPLOAD_SUCCESS: 'Files successfully uploaded',
  ENTER_DEFAULT_DEPTID: 'Please select a default department id to continue',
  CHARACHTER_LENGTH: 'The note exceeds the maximum character count.',
  SHARE_TO_GLOBAL_REQUIRED_WARNING: 'Please select at least one file to proceed',
  SHARE_VIA_EMAIL_REQUIRED_WARNING: 'Please select at least one file to proceed',
  SHARE_VIA_EMAIL_SUCCESS: 'File(s) shared successfully',
  FILES_SUBMITTED_TO_UPLOAD_QUEUE: 'File(s) successfully queued. Files will be uploaded to server in the background.',
  FILE_QUEUED_AND_WAITING: 'File queued. Waiting to upload...',
  FILE_UPLOADING: 'File is uploading to the server...',
  FILE_UPLOAD_SUCCESS: 'File successfully uploaded to server.',
  SHARE_VIA_EMAIL: 'Please select at least one file to proceed',
  SHARE_EMAIL_ERROR: 'Please select at least one TO user.',
  DESIGN_REPORT_DOWNLOAD_REQUEST_SUCCESS: 'Your request has been sent successfully',
  RECORD_ALREADY_EXISTS: 'Record already exists',
  SAMPLE_TYPE_REQUIRED: 'Sample type is required'
}
